/*
 * This source file was generated by the Gradle 'init' task
 */
package com.frc7028.physics.sim;

import static com.frc7028.physics.sim.BallisticPrecomputer.ShotParameters;

import com.frc7028.physics.sim.BallisticPrecomputer.RobotState;
import com.frc7028.physics.sim.BallisticPrecomputer.ShotParameters;
import edu.wpi.first.math.geometry.Rotation3d;
import java.util.function.Function;

public class App {
  public BallisticPrecomputer precomputer;

  public App(
      SimulatorResolution simulatorResolution,
      IntegratorResolution integratorResolution,
      BallisticEnvironmentProfile environmentProfile,
      FieldMetrics fieldMetrics,
      Function<Double, Rotation3d> speedToSpin,
      Function<RobotState, ShotParameters> computeGuessShot) {
    this.precomputer = new BallisticPrecomputer(
        simulatorResolution,
        integratorResolution,
        environmentProfile,
        fieldMetrics,
        speedToSpin,
        computeGuessShot);
  }

  public static void main(String[] args) {

  }
};